#!/usr/bin/env python3.7
import os

os.putenv(STAGE,'good')
stage = os.environ["STAGE"].upper()
output = f"We're running in {stage}"

if stage.startswith("PROD"):
   output= "DANGER!!! - " + output
print(output)
