#!/usr/bin/env python3.7

#BMI = (weight in kg / height in square meters)
#Imperial version = BMI * 703

def gather_info():
#    while True:
    height = float(input("Enter your height? (inches or meters) "))
#       if height is str:
#          print("good value")
#          break
#       else:
#          print("Invalid")
    weight = float(input("Enter your weight? (pounds or kg) "))
    system = input("are your entries in metric or imperial").lower().strip()
    return (height, weight, system)
#print (gather_info())
def calculate_bmi(weight, height, system='metric'):
    """
    Return the Body Mass Index (BMI) for the
    given weight, height, and measurement system.
    """
    if system == 'metric':
        bmi = (weight / (height ** 2))
    else:
        bmi = 703 * (weight / (height ** 2))
    return bmi

while True:
    height, weight, system = gather_info()
    if system.startswith('i'):
        bmi = calculate_bmi(weight, system='imperial', height=height)
        print(f"Your BMI is {bmi}")
        break
    elif system.startswith('m'):
        bmi = calculate_bmi(weight, height)
        print(f"Your BMI is {bmi}")
        break
    else:
        print("Error: Unknown measurement system. Please use imperial or metric.")
