#!/usr/bin/python3
import os, sys, glob, yaml
os.chdir("/home/kajijola/kola/dev/Ansible_Inventory_Cloud/inventory/CloudHosting/SAIT/PA")
a=[]
for d in glob.glob("/home/kajijola/kola/dev/Ansible_Inventory_Cloud/inventory/*/*/PA/host.yaml"):
    print(d)
    a.append(d)
for b in a:
    with open(b) as f:
      list_doc = yaml.load(f)
      #print (list_doc)
    #for sense in list_doc:
    if "host_jira_schoolname" in list_doc and  list_doc["host_jira_schoolname"] == "SAIT":
         list_doc["host_purchase_reservation"] = 12
       #print (sense)
    with open(b, "w") as f:
      yaml.dump(list_doc, f)
